updates

diff --git a/.github/actions/build-deploy/action.yaml b/.github/actions/build-deploy/action.yaml
--- a/.github/actions/build-deploy/action.yaml
+++ b/.github/actions/build-deploy/action.yaml
@@ -5,14 +5,25 @@ inputs:
     description: 'Branch name to determine build or deploy'
     required: false
     default: ''
+    project-path:
+      description: 'Path to the Maven project'
+      required: true
 runs:
   using: "composite"
   steps:
+    - name: Validate project path
+      shell: bash
+    - run: |
+        POM="${{ inputs.project-path }}/pom.xml"
+        if [ ! -f "$POM" ]; then
+          echo "::error::Cannot find Maven project at $POM"
+          exit 1
+        fi
     - name: Build or Deploy
       shell: bash
       run: |
         if [[ "${{ inputs.branch }}" == "main" ]]; then
-          mvn -B -e -U deploy -DskipTests=true -DskipITs=true -s ./settings.xml
+          mvn -f "${{ inputs.project-path }}/pom.xml" -B -e -U deploy -DskipTests=true -DskipITs=true -s ./settings.xml
         else
-          mvn -B -e -U clean install
+          mvn -f "${{ inputs.project-path }}/pom.xml" -B -e -U clean install
         fi
